version: '3'

services:
  payload:
    container_name: trust-company-payloadcms
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    env_file:
      - .env.production

volumes:
  node_modules:
