version: '3'

services:
  payload:
    container_name: trust-company-payloadcms
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./media:/home/node/app/media
    working_dir: /home/node/app/
    env_file:
      - .env.production
    restart: always
